version: '3'

services:
  ipa-toolkit-frontend:
    container_name: ipa-toolkit-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 18-bullseye
    volumes:
      - ..:/workspace
    command: sleep infinity
    networks:
      - ipa-toolkit-network

networks:
  ipa-toolkit-network:
    external: true
