name: Continuous integration

on: push

jobs:
  build:
    name: Build, lint, and test on Node 18
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check format
        run: yarn run check:format

      - name: Check types
        run: yarn run check:types

      - name: Run tests
        run: yarn run test

      - name: Build
        run: yarn run build
