name: Release new application image

on:
  push:
    tags:
      - v*

jobs:
  push-to-registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/ictorg/ipa-toolkit-frontend:latest
          cache-from: type=registry,ref=ghcr.io/ictorg/ipa-toolkit-frontend:latest
          cache-to: type=inline

      - name: Create Github release
        run: yarn run release:create-github-release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
